name: Build

on:
  pull_request:
    branches:
      - develop

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: chmod cache key
        run: chmod +x ./scripts/checksum.sh

      - name: Generate cache key
        run: ./scripts/checksum.sh app checksum.txt

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Check Spotless
        run: ./gradlew spotlessCheck --init-script gradle/init.gradle.kts --no-configuration-cache --stacktrace

      - name: UnitTest
        run: |
          ./gradlew testDebugUnitTest --stacktrace

      - name: Check Kover
        run: |
          ./gradlew koverXmlReportDebug

      - name: Display local test coverage
        uses: madrapps/jacoco-report@v1
        with:
          title: test coverage report
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          update-comment: true
          skip-if-no-changes: true
          continue-on-error: false
          paths: |
            ${{ github.workspace }}/**/build/reports/kover/reportDebug.xml
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload lint reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: app/build/reports
